// <auto-generated />
namespace NewEnrollmentApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migration041419 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration041419));
        
        string IMigrationMetadata.Id
        {
            get { return "201904141720458_migration041419"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
